### ISSUE TITLE
Feature 1 : User can add a vehicle with vehicle details to their 'garage' list.

### ISSUE THREAD

**Issue by aaron-j-butnik** [aaron-j-butnik/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a vehicle with vehicle details from a form to their 'garage' list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.  

When clicking on the 'add vehicle' button, a form will be rendered where the user can enter their vehicle information.  They can then either hit a 'save' button to add the vehicle to their vehicle list, or hit cancel to close the form and return them to the homepage. h

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103544497/210102039-0b763468-58b9-492c-af44-0a518275f094.png)
![image](https://user-images.githubusercontent.com/103544497/210024041-a3659ed7-1a34-4f7e-9e9b-5ea2c53cd6b2.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Create database through the command line with createdb vehicleServiceTracker.
- [x] Copy and paste the schema from DB Designer into the schema.sql.
- [x] Update data.sql with some dummy data for testing purposes.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] Create a POST route that has a route '/api/vehicleData'
- [x] Destructure the year, make, model, license plate, current odometer, and additional notes from the req.body object.
- [x] Check to see if all entries are given, if not throw a new client error.
- [x] Add sql code to insert values into database.
- [x] Create param variables for sql code.
- [x] Query the database with sql code and params as arguments.
- [x] Then add callback function with parameter result and destrucre entries from result.rows.
- [x] Catch all potential errors.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create app component to handle hash routing and page state.
- [x] Create a vehicle-entry-form component page. 
- [x] Create and incorporate navbar component.
- [x] Create a from react element that will have entries for vehicle data.
- [x] Create a handle submit event listener that will call the fetch function to add the entry to the vehicleId database.
- [x] Add necessary css to reflect the wireframes.
- [x] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
