### ISSUE TITLE
Feature 2: User can edit vehicle details

### ISSUE THREAD

**Issue by aaron-j-butnik** [aaron-j-butnik/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit vehicle details
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click on the 'edit vehicle' button, which will bring up the edit vehicle page, with a form where they can enter new vehicle details about their vehicle. They can then hit save to save the data, or cancel to cancel.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103544497/210103575-5745a556-b28e-47a5-b8d8-2b3dc3dcea2a.png)
![image](https://user-images.githubusercontent.com/103544497/210103596-42f3200b-da10-4bb1-b97f-386cfb8fe39d.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] Create a put method for editing vehicle data in the database.
- [x] Create conditional statement to throw errors if necessary information is not included.
- [x] Update vehicle data using sql update.
- [x] Create params for sql values.
- [x] Query the database using sql, and params.
- [x] Create 'then' promise for result status and vehicle data.
- [x] Catch and errors.
- [x] Test with HTTPie.
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for edit vehicle form, for user input.
- [x] Within edit vehicle component:
- [x] Define a class component for EditVehicleForm, and export it. 
- [x] Create a state for input values.
- [x] Create a handleInput method.
- [x] Create a handleSubmit method.
- [x] In handleSubmit create a fetch method which uses "PUT".
- [x] Add 'then' promises and handle and errors.
- [x] Create a render method with necessary CSS for form to reflect wireframe.
- [x]  Create an 'edit-vehicle-page' within the pages directory.
- [x] Create an EditVehiclePage function, and export that function.
- [x] Create necessary CSS to reflect wireframe.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
