### ISSUE TITLE
Feature 3: User can add service performed on their vehicle.

### ISSUE THREAD

**Issue by aaron-j-butnik** [aaron-j-butnik/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a service performed on their vehicle.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click on the 'add service' button to bring up the 'add service page' and enter service data performed on their can, which will be added to the database. They can then hit either a 'save' button to save data or 'cancel' button to go back to 'my garage' page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103544497/210104104-dfa3b74a-a223-4b68-bc9c-3454fc02e92f.png)
![image](https://user-images.githubusercontent.com/103544497/210104151-2ae80226-d351-4d2c-8400-7dd44c1a6ab8.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] Create a post route for a vehicle that will add service data to database.
- [x] Enter vehicle service data using sql code.
- [x] Create params for sql code for security purposes.
- [x] Query the database using sql code and params.
- [x] Send response using the then method, and catch any errors on the server side.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for user to input service data.
- [x] In service form component...
- [x] Create a state for service form.
- [x] Create a handleInput method.
- [x] Create a handleSubmit method.
- [x] Within handleSubmit method create a fetch POST route to update backend with user input for service data. 
- [x] Create proper JSX and CSS to reflect wireframe for service data form.
- [x] Create a component in Pages directory for add-service-page.jsx.
- [x] Create proper JSX and CSS for service page.
- [x] Update App component with proper hash route.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
