### ISSUE TITLE
Feature 4: User can edit a service on their vehicle.

### ISSUE THREAD

**Issue by aaron-j-butnik** [aaron-j-butnik/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit a service on their vehicle.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click on the 'edit service' button on the 'My Services' page which will bring up the 'edit service' form. They can then click on the 'save' button to update the service data in the database, or the cancel button to go back to the service page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103544497/210104443-ef56d149-089e-4595-994d-4898ecee8353.png)
![image](https://user-images.githubusercontent.com/103544497/210104464-623ff962-8558-40de-8e1d-a870787bbe7c.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] Create a 'PUT' route to update service data.
- [x] Within PUT route get serviceId through req.params.
- [x] Get service data through req.body.
- [x] Add conditionals for necessary input fields with ClientError messages for incorrect user inputs.
- [x] Create sql code for updating specific service.
- [x] Create params variable for sql code.
- [x] Query the database using sql code and params.
- [x] Add '.then' method for returning status and data.
- [x] Add '.catch' method for catching any server side errors.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a edit-service-form component for service form.
- [x] Within -edit-service-form set state of component.
- [x] Create a componentDidMount method that contains a fetch GET  method for updating service form with previously entered user data.   Set state with previous user data. Catch any errors.
- [x] Create a handleInput method that will set the state with new values for user inputs.
- [x] Create a handleSubmit method that contains a fetch PUT method for updating new user inputs.
- [x] Within fetch PUT method create '.then' methods for response and data.  
- [x] Handle any errors within fetch PUT method.
- [x] Create a render method to return proper JSX with CSS styling to reflect wire frame.
- [x] In Pages directory, create a edit-service-page to hold edit-vehicle-form component.
- [x] Create proper CSS to reflect wireframe.
- [x] Update App component with proper hash routing path to navigate to edit-vehicle-page.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
