### ISSUE TITLE
Feature 5: User can delete a service. 

### ISSUE THREAD

**Issue by aaron-j-butnik** [aaron-j-butnik/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete a service. on their vehicle.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking on the delete button on the service page will delete the service from the database. When clicking the 'delete' button a confirmation modal will pop up. The user can then click the 'delete' button to confirm, or cancel button to cancel.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/103544497/210104922-4f050647-fdcf-4284-8681-7e28b0d53607.png)
![image](https://user-images.githubusercontent.com/103544497/210105020-29f3962f-a6be-4aea-af4f-2a0014bab7f6.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...
- [x] Create a delete route to delete an individual service from the database.
- [x] Within delete route get serviceId from req.params.
- [x] Create sql code for deleting a service from the database.
- [x] Create params for serviceId.
- [x] Query the database and pass in sql and parmas variables as arguments.
- [x] Then create a then method that will return the result status and json data.
- [x] Catch any errors from the backend.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component for modal called delete-modal.
- [x] Within delete-modal: 
- [x] Create a render method with proper jsx and css for modal.
- [x] Create a deleteServiceId method.
- [x] Within deleteServiceId method, create a fetch delete route for an individual service (serviceId).
- [x] Respond with applicable json, and handle any errors.
- [x] Rerender the page.
- [x] Catch any errors and with catch method.
- [x] Import and export proper components.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
